### ISSUE TITLE
Remove ceiling of referencing

### ISSUE THREAD

**Issue by ssbarnea** [p1c2u/jsonschema-path#143]
Please consider removing the ceiling on referencing. If there is a known reason for this ceiling, I was not able to find it inside a comment or even using git blame.
```
referencing = ">=0.28.0,<0.35.0"
```
https://github.com/p1c2u/jsonschema-path/blob/main/pyproject.toml#L48

A veiling should be introduced only when we already know that a newer version breaks it, and even when this happens, it should include a link to either upstream issue, or local issue.

If there is a desire to ship something that was effectively tested, an optional `extra` could be used that can even have exact pins of the dependencies. I used this approach on many projects as it can prove handy for some users.

In my particular care, this prevented the use of dependabot by causing a conflict and I had to disable the updates for `referencing` temporary to allow it run on the others.
```
The conflict is caused by:
    jsonschema 4.22.0 depends on referencing>=0.28.4
    jsonschema-path 0.3.2 depends on referencing<0.32.0 and >=0.28.0
    The user requested (constraint) referencing==0.35.1
```

**Comment by p1c2u** [comment]
We can't remove because it's unstable 0.x version branch but for sure we can upgrade.

**Comment by ssbarnea** [comment]
Lots of libraries keep using `0.` versioning for their entire lifespan. I am not sure if we can rely on SerVer meaning on this, it would be more of case by case decision based on how each of them is maintained (how many tests they have and how often they decide to break). Based on my experience ~4/5 are safe.
