### ISSUE TITLE
Support referencing 0.32.0

### ISSUE THREAD

**Issue by mwgamble** [p1c2u/jsonschema-path#98]
By not allowing `referencing` v0.32.0, it's causing a dependency resolution failure with pip-tools when also using `moto`.

**Comment by kapilt** [comment]
the dependency specification on this should be loosened ^0.3 , tight coupling to dependency versions in a library is generally problematic.

**Comment by kapilt** [comment]
never mind ic why it was done re incompatibility inbound on receiver callbacks,  https://github.com/python-jsonschema/referencing/issues/75 however 0.32.0 does not contain that change fwiw
https://github.com/python-jsonschema/referencing/blob/main/docs/changes.rst

**Comment by kapilt** [comment]
pr already up for the update https://github.com/p1c2u/jsonschema-path/pull/100

**Comment by flaeppe** [comment]
Would it be possible to lower bound the `referencing` to `0.32` (e.g. `>=0.32`), or `0.33` if the backwards incompatibility was released there, in a next/future release?
